.travis.yml
CHANGELOG.md
Cargo.toml
README.md
examples/delay.rs
examples/led.rs
src/gpio.rs
src/lib.rs
src/prelude.rs
src/rcc.rs

Hi there!
This is a WIP pull request to support the STM32F100 which is on the valueline discovery board.
It looks like not all chips supported by `stm32f1` are supported by this HAL wrapper. Maybe they should be added to the `features` list in `Cargo.toml` as they become supported? 
I've added a `stm32f100` feature. PWM is disabled for the moment until I figure out how to fix the `.ccr()`-not-found problem.
A version of  `led.rs` on PC8 (with an `.set_high()` call that was missing) was tested and working. I'm going to have a look at timers and delays next. The ultimate goal is to be able to use this crate along with https://github.com/JohnDoneth/hd44780-driver

stm32f100 - compiles, but PWM broken

---

CHANGELOG.md
examples/blinky_rtc.rs
examples/rtc.rs
src/backup_domain.rs
src/lib.rs
src/rcc.rs
src/rtc.rs

This is essentially the same code as the one in https://github.com/japaric/stm32f103xx-hal/pull/98 and it still has some issues.
The main problem is that LSE initialization and rtc clock selection has to happen before clock freeze. However, in order to do that, the backup domain has to be enabled in the pwr register. Since freeze, or any other function dealing with rcc does not modify pwr, adding that as a parameter would be a breaking change.
Additionally, we want to statically ensure (I think) that the required clocks are on when the real time clock is started. There are a couple of solutions to this
My current solution to all this is to add a function to rcc that sets up things in the backup domain which gives a token that is required in order to run the rtc.
I'm not a huge fan of that …

Add support for real time clock

---

src/serial.rs

For both stm32f100 and stm32f103 families USART1 is clocked by PCLK2, and all other USARTS by PCLK1.
I've checked ref manuals for both families. And it fixes baud rate on my f103.

Fix mixed up USART clocks

---

examples/blinky.rs
examples/blinky_rtc.rs
examples/led.rs

Fix for #26 
This seems to have been broken in #20 where the affected line was changed from `gpioc.pc13.into_push_pull_output(&mut gpioc.crh);` to `gpioc.pc13.into_push_pull_output(&mut gpioc.crh).set_high();`
I think explicitly calling `set_low` is better than the previous case since it's more explicit and as far as I know, we don't specify wether or not pins will be high or low after `into_push_pull_output`. Or was there a reason `set_low` wasn't explicitly called?

Fix broken LED example (#26)

---

examples/pwm_input.rs
src/lib.rs
src/pwm_input.rs

Hello !
I gave a try at implementing pwm input for the stm32f103, it was not tested (yet!) but the implementation is well documented.
Could you take a first look at it and tell me if you spot something wrong ?
Current features :
* Define which pins can be used for PwmInput
* Configure a timer in PwmInput mode
* Automate PRESC and ARR calculation
* Read a frequency or a duty cycle from a timer in PwmInput mode
* Implement PwmInput for TIM2, TIM3, TIM4
Thank you ! :smile:

Implement pwm input for TIM2, TIM3, TIM4

---

examples/blinky.rs
examples/serial.rs
src/lib.rs

As a step towards closing #37 I want to start improving the documentation of this crate and I think the examples are a good place to start. I added a bunch of comments to the blinky and serial examples which try to explain what each line in the example does.
I also improved the main crate documentation page by adding the blinky example to it and clarifying how to specify the crate as a dependency. I also kind of think we should do that to the readme since that's where people will first encounter the crate, is that a good idea?
I intend to give the rest of the examples similar treatment, but I would like some feedback on the two examples that are already done so I don't make the same misstakes in *all* of them :). I'm not sure if we should make all of them this verbose, especially for the …

Improve example documentation

---

src/dma.rs
src/i2c.rs
src/rcc.rs
src/serial.rs
src/spi.rs

Another small PR before releasing to crates, hopefully you don't mind the spam but code review tends to be useful.
I commented out the things which are clearly DMA related and removed the rest of the unused code.
I'm a bit confused as to why the `mut` aren't required in `i2c.rs` but if the compiler is fine with it, I suppose it's not an issue.

Fix warnings

---

CHANGELOG.md
src/lib.rs
src/prelude.rs
src/pwm.rs

Crate stm32f1 handles CCRx registers differently for stm32f103
and for all the other supported MCU families. As a result,
naming conventions to access CCRx fields  are not the same.
Enable support for PWM on stm32f100 using 'feature' switch to
distinguish between stm32f103 and other MCUs at compile time
and use the correct CCRx field names.

Enable PWM for stm32f100

---

CHANGELOG.md
src/gpio.rs

Add full range of GPIO pins corresponding to LQFP-100 package
including PC/PD/PE. Unify pin definitions for both supported
stm32 mcu families.

RFC: add gpio pins for LQFP-100 package

---

.travis.yml
CHANGELOG.md
Cargo.toml
README.md
examples/delay.rs
examples/led.rs
src/lib.rs
src/rcc.rs
src/timer.rs

Add feature to enable support for stm32f101 chips.
Note that TIM1 is excluded since only stm32f100
and stm32f103 chips contain advanced timers.

Add feature to support stm32f101 chip

---

CHANGELOG.md
examples/adc.rs
src/adc.rs
src/lib.rs
src/prelude.rs
src/rcc.rs

Summary
-------------
This PR adds the following bits:
- implement ADC clock configuration in rcc module
- implement ADC support, including multiple ADC blocks
- add ADC example
This PR is based on #19 by @TheZoq2 . As per request from @therealprof , it has been reworked following stm32f0x ADC implementation. Besides, some implementation details follow stm32f4x ADC implementation.
Limitations
-------------
1. Basic one-shot support only: similar to what we have in stm32f0x, but not in stm32f4xx
2. No dual ADC mode support when 2 ADC blocks are available
3. No fool proof against using the same channel in two ADC blocks.
Implementation notes
-------------
1. Split of ADC implementation to simplify review
To simplify review, ADC implementation is split into the following two parts: 
- 2nd …

RFC: add support for ADC

---

CHANGELOG.md
Cargo.toml
examples/timer-interrupt-rtfm.rs
src/timer.rs

Very simple methods but potentially useful, especially the one to clear the update interrupt flag.
I was having trouble using the timer with interrupts, because the Timer takes ownership of the registers and the `tim` field is private.
Sorry if I got something wrong, I am kinda new to rust.

Adds some simple methods to Timer.

---

examples/pwm_input.rs
src/pwm_input.rs

It seems that I made a mistake in #10 as the gpio where not properly configured. I don't know why our tests worked, but this PR fix this issue.
Here is a screenshot of the reference manual, p166 (table 23).

Fix gpio configuration for pwm input

---

src/rcc.rs

Discussion started in https://github.com/stm32-rs/stm32f1xx-hal/issues/62 so I'll just copy description from there:
When enabling standby mode, there is a need to set `PWREN` bit in APB1 ENR register.
Right now it can be achieved by calling `constrain` on `rcc.bkp`. https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/rcc.rs#L367
And while it does set the right bits in the right places, it enables other registers as well, which may to may not be desirable.
Ideally, I'd like to be able to do it manually:
```
rcc.apb1.enr().modify(|_r, w| {
w.pwren().set_bit()
});
```
Or maybe just call a function that does it for me, something like what `set_sleepdeep()` does: https://github.com/rust-embedded/cortex-m/blob/master/src/peripheral/scb.rs#L585
```
rcc.apb1.set_pwren();
```
---
As …

Add public functions to toggle PWREN bits

---

CHANGELOG.md
examples/pwm.rs
examples/pwm_custom.rs
src/pwm.rs

Hi all,
In practical applications various selections of PWM channels may be needed. For instance, one or two channels attached to gpio pins for non-default remapping. It is possible to keep adding implementations of the 'Pins' trait into pwm module for all the needed channel/pin combinations. However it does not look practical unless there exist some clever way to describe all possible combinations w/o boilerplate code.
Another option is to keep only basic implementations in pwm module, e.g. 'all the channels for default pin remapping'. As for the custom channel selections, it is possible to use newtype pattern to implement 'Pins'  trait in the user application. This PR adds documentation and example demonstrating the use of newtype pattern for creation of custom PWM channel …

RFC: docs and examples for custom selection of PWM channels

---

CHANGELOG.md
examples/serial-dma-circ.rs
examples/serial-dma-peek.rs
examples/serial-dma-rx.rs
examples/serial-dma-tx.rs
examples/serial_config.rs
src/serial.rs

This PR adds the the ability to configure the stop bits and parity bits of the serial device. It is inspired by the implementation in the f4 hal but it does differ a bit from that.
The main difference is that this implementation doesn't allow you to specify word length which I did for 2 reasons:
- Reading/sending 9 bits would require using a u16 instead of u8
- "Word length" includes parity bits
The second point means that a device configured to send 9 bit words with one parity bit actually sends 8 bit words and the parity bit. This seems to go against the way UART protocols are usually defined. To avoid that confusion, I decided to just disable the option of changing word size and assume the user wants to send 8 bits of actual data.
Another difference to the f4 impl is that I don't use a …

Add more configuration options to UART

---

CHANGELOG.md
examples/adc.rs
examples/adc_temperature.rs
src/adc.rs

Add reading methods to read from ADC1 special channels:
- channel 16: temperature sensor
- channel 17: internal reference voltage
Note that these methods should be implemented only for ADC1 block
since in ADC2 and ADC3 those channels are connected to Vss.

adc: add support for channels 16 and 17 in ADC1

---

CHANGELOG.md
src/serial.rs

This PR adds listen and unlisten to Tx and Rx, acting identically to Serial::listen/unlisten(Txe/Rxne).
(I'm not super happy with the duplication here, but it didn't seem trivial to extract it to a helper. Let me know if you want me to do so.)

Implement serial::{Tx,Rx}::{listen,unlisten}.

---

CHANGELOG.md
examples/nojtag.rs
examples/pwm_custom.rs
examples/pwm_input.rs
src/afio.rs
src/gpio.rs

At startup, pins used by the debugger are in `Debugger` state, prohibiting their
use. `disable_jtag` allow to get PA15, PB3 and PB4 usable as GPIO or alternate
functions at the cost of disabling JTAG.
Discussed in #77 
cc @MauroMombelli

Handle debugger pins

---

src/pwm.rs

Fix copy-paste errors and implement Pins trait properly for TIM3 PWM,
where PC8 and PC9 pins are configured as its two channel channels.

pwm: fix examples for custom Pins trait

---

CHANGELOG.md
src/rcc.rs

Closes https://github.com/stm32-rs/stm32f1xx-hal/issues/84 .

Fixes hclk miscalculation

---

src/gpio.rs

cc @therealprof 
Can this affect on debug builds?

gpio consts

---

CHANGELOG.md
src/backup_domain.rs

This is my first attempt at fixing issue #83.

Add support for reading and writing to the Backup Data Register (#83).

---

CHANGELOG.md
examples/blinky.rs
examples/pwm.rs
examples/pwm_custom.rs
examples/pwm_input.rs
examples/qei.rs
examples/timer-interrupt-rtfm.rs
src/lib.rs
src/prelude.rs
src/pwm.rs
src/pwm_input.rs
src/qei.rs
src/timer.rs

cc @TheZoq2 
cc @therealprof 
```rust
// Simple count down timer
let mut timer = Timer::syst(cp.SYST, &clocks)
.start_count_down(1.hz());
// or
let timer = Timer::tim1(device.TIM1, &clocks, &mut rcc.apb2);
...
let mut timer = timer.start_count_down(1.hz());
timer.listen(Event::Update);
/// PWM
let mut pwm = Timer::tim4(p.TIM4, &clocks, &mut rcc.apb1)
.pwm((c1, c2, c3, c4), &mut afio.mapr, 1.khz())
.3;
// PWM input
let mut pwm_input = Timer::tim3(p.TIM3, &clocks, &mut rcc.apb1)
.pwm_input(
(pb4, pb5),
&mut afio.mapr,
&mut dbg,
Configuration::Frequency(10.khz()),
);
```
See #89 
Timer now contains `clk: Hertz` instead of full `clocks: Clock` structure (reduce code size in debug mode).

split Timer on 2 stage

---

CHANGELOG.md
Cargo.toml
src/adc.rs
src/dma.rs
src/serial.rs

cc @therealprof 
Use as_slice/as_mut_slice for dma buffers, as as_ref restricted by 32-sized buffers.

as_slice instead of as_ref

---

CHANGELOG.md
examples/blinky_rtc.rs
examples/pwm_input.rs
examples/rtc.rs
examples/serial_config.rs
src/rtc.rs
src/timer.rs

Closes https://github.com/stm32-rs/stm32f1xx-hal/issues/89 and closes https://github.com/stm32-rs/stm32f1xx-hal/issues/41.
Right now it would be ok to leave the URS bit set, since the HAL has ownership over the registers and we don't implement anything which requires URS bit cleared. However, I decided to clear the URS bit after the update event to prevent future side effects, but I don't have strong feelings about that...

Improve time keeping with Timer and RTC

---

CHANGELOG.md
src/afio.rs
src/i2c.rs
src/pwm.rs
src/pwm_input.rs
src/qei.rs
src/serial.rs
src/spi.rs

This stack exchange post explains the issue pretty well https://electronics.stackexchange.com/questions/260757/timer1-remap-cause-debug-crash-on-stm32f103
The SWJ_CFG bits are write only, meaning that reads are undefined. On the blue pill, reads seem to work fine anyway, but on the RGT6, they return some other value which messes with the debug port.
My fix for it is to make the `mapr` function private, and only allow modifications via the `modify_mapr` function which remembers the state of the debug port and writes the config accordingly.
Since `mapr` was public, this is a breaking change. I see no reason to have it public, in fact, users can break the abstractions by modifying `mapr` so this new `modify_mapr` function is marked `pub(crate)`

Rewrite SWJ config when modifying MAPR (fixes #105)

---

examples/serial-fmt.rs
src/serial.rs

This fixes issue #110.
Also add example `serial-fmt` for using writeln! with serial Tx.

Re-add core::fmt::Write for serial Tx

---

src/lib.rs

Only allow exactly one target "feature" to be set at any time, as discussed in #112 and discord.
Otherwise a compile-time error message will be given.
Is the "greater than one target specified" case useful to error on as well?
The "zero target specified" case has a confusing message about missing imports and methods, but the compiler has a message which might already be close enough.
```bash
error[E0252]: the name `pac` is defined multiple times
--> src\lib.rs:104:9
|
101 | pub use stm32f1::stm32f100 as pac;
|         ------------------------- previous import of the module `pac` here
...
104 | pub use stm32f1::stm32f101 as pac;
|         ^^^^^^^^^^^^^^^^^^^^^^^^^ `pac` reimported here
|
= note: `pac` must be defined only once in the type namespace of this module
help: you can use `as` to …
```

error on any invalid target combination

---

README.md

Update `README.md` to explain how to give `cargo run` permission to launch `gdb`.
As discussed in discord and #113, on first-run the gdb debugger doesn't give `cargo run` permission to run `gdb` automatically and load the FW to the HW.
This PR updates the `README.md` to show a command which can give this permission, and limits the permission addition to the scope of the `stm32f1xx-hal` repository in use.
Because of the different conventions between Linux and Windows, the two commands were unable to be distilled into the same line of text.
It is unknown if only the Linux example is wanted, and the windows version of the command should be removed?
It seems the `README.md` already makes this assumption elsewhere?
Suggestions are welcome.

README explain cargo run permission for gdb #113

---

CHANGELOG.md
examples/blinky_generic.rs
src/gpio.rs

This adds the generic pin enum which spun out of #114 
I'm not sure if only having the downgrade function on the already downgraded pins is a good idea as you'd have to do `.downgrade().downgrade()` if you want to go all the way, which I imagine is the thing people want to do most often. Actually, do we even have a use for the half downgraded pins anymore?
This has a fair amount of code duplication, do you think I should make another macro to automatically impl the individual functions. Or should we use the enum_dispatch crate? I'm not a huge fan of adding external dependencies for a single use, mainly for security concerns, but perhaps someone disagrees.
Also, for now this is untested on actual hardware, but I don't see any reason it wouldn't work since it's just an alias.

Implement more general GPIO pins

---

CHANGELOG.md
examples/spi-dma.rs
src/spi.rs

This adds basic support for transmitting data over SPI using DMA.
Since this is a basic implementation, only non-circular buffers are supported. However, at the moment I don't have a need for that, and I think we might have to restructure some DMA stuff for simultaneous TX and RX support so I don't want to put too much effort into this until we get around to that.
I think RX support might be fairly easy, but it would require reconfiguring the SPI device as reads happen on writes in bidirectional mode.
*Note*: I have yet to test DMA over SPI2, I'll do that tomorrow but the code probably shouldn't change

Add unidirectional SPI DMA

---

CHANGELOG.md
src/timer.rs

Quick fix to prevent configuring pwm_input clobbering the dbg.cr register.
The issue I was having was ITM was breaking after the call to stop_in_debug in timer.rs because part of the ITM config lives in dbg.cr and the call to write was resetting everything to 0.
I had a quick scan for other similar issues in timer.rs but didn't see any.

Changed timer stop_in_debug to modify dbg.cr instead of overwriting it

---

CHANGELOG.md
README.md
src/gpio.rs
src/rtc.rs
src/serial.rs

 replace Void with Infallible + small fixes

---

CHANGELOG.md
Cargo.toml
examples/usb_serial.rs
examples/usb_serial_interrupt.rs
examples/usb_serial_rtfm.rs
src/lib.rs
src/usb.rs

See also: https://github.com/stm32-rs/stm32-usbd/pull/16

Add USB driver

---

CHANGELOG.md
src/i2c.rs
src/time.rs

In #127 I realised that i2c doesn't use the Hertz structs to set freuency. This seems strange, so I fixed it.
Unlike the other peripherals, this doesn't allow construction from `KiloHertz` or `MegaHertz` as that would have required making the `mode` struct generic, which would propagate a lot. It might still be a good idea to do so, though perhaps it's better to pass the frequency separately to the i2c "constructor". This would require less generics.

Set i2c frequency using Hertz

---

CHANGELOG.md
README.md
src/adc.rs
src/lib.rs
src/pwm_input.rs
src/rcc.rs
src/timer.rs

I've added all the timers according to the CubeMX database with the correct device & density flags.
The only one's I've had to comment out are 9, 10, 12, 13 and 14 on some devices because fields for these are missing from the underlying pac. The code is there to enable them when stm32-rs fixes up those SVDs.
This might be a minor breaking change as previously some of the devices had timers enabled that aren't actually available across the whole range - the fix is to add the appropriate density feature. I've added some info about this to the README so hopefully people will find this without a problem.
There's also some minor formatting stuff mostly from rustfmt in case you are wondering about the whitespace changes in pwm_input.
I should also draw your attention to the fact I added …

Added all timers for all variants as described by CubeMX

---

src/lib.rs
src/rtc.rs
src/timer.rs

Resolves #139 
I temporary added `#![deny(unused_unsafe)] and built all variants to find the instances of unused unsafe. Turned out there were only two left after the recent PAC update.

Removed crate level allow(unused_unsafe) in favour of attributes on the specific instances

---

CHANGELOG.md
examples/pwm_custom.rs
src/gpio.rs
src/pwm.rs
src/pwm_input.rs
src/qei.rs
src/timer.rs

This is something average between #124 and #146.
But it's need for testing.
cc @geomatsi

Pwm remap: another try

---

Cargo.toml
examples/pwm.rs
src/lib.rs
src/pwm.rs
src/qei.rs
src/timer.rs

This fixes #144, both in terms of making that example compile without extra features, and documenting the features.
While i'm at it, I also updated the PWM and timer docs, and cleaned up `Cargo.toml`

Documentation updates and cleanup

---

src/i2c.rs

This PR fixes some issues I had with I2C.
I wanted to query exactly 2 bytes over I2C, but I got an I2C arbitration error.
Because of this I fixed the code to follow exactly the rules described [here](http://st.com/content/ccc/resource/technical/document/application_note/5d/ae/a3/6f/08/69/4e/9b/CD00209826.pdf/files/CD00209826.pdf/jcr:content/translations/en.CD00209826.pdf).
Now it is working fine for me.
Example code:
```rust
#![no_std]
#![no_main]
use cortex_m::iprintln;
use cortex_m_rt::entry;
use mpu6050::*;
use stm32f1xx_hal::{delay::Delay, i2c, prelude::*, stm32};
#[allow(unused_imports)]
use panic_itm;
#[entry]
fn main() -> ! {
let device = stm32::Peripherals::take().unwrap();
let mut cp = cortex_m::Peripherals::take().unwrap();
let stim = &mut cp.ITM.stim[0];
let mut flash = …
```

Fixed I2C reading problems

---

examples/exti.rs

the `exti` and `EXTI` variables are actually references to a pin and not to the Interrupt controller.
The interrupt controller registers are `p.EXIT`.
Therefore, I changed the variable name to reduce confusion.

Changed Variable name in EXTI example

---

src/lib.rs

The cargo argument is `--features`, not `--feature`.

Fix compile error for missing model feature

---

CHANGELOG.md
examples/serial.rs
src/serial.rs

Fixes #167.
I managed to implement this without having split tx/rx pins in the `Serial` struct thanks to the help of @Disasm. Instead, it uses a private trait (`UsartReadWrite`) to avoid having duplicated peripheral access logic. There should be no breaking change in this PR.

Impl Read<u8> / Write<u8> for Serial

---

examples/qei.rs
src/qei.rs

This PR adds the `QeiOptions` struct which allows configuration of the timer slave mode (affecting QEI) and the QEI auto reload register value. There's also some minor formatting noise so apologies for that.
I've tested this on a Blue Pill with a CNC jog pendant that produces 400 PPR. Seems to work well.
I'm unsure of the names for everything added. They're taken almost verbatim from the datasheet, but aren't very descriptive or intuitive. Should we bikeshed this or leave it as is for now?

Add configuration options to QEI interface

---

Cargo.toml
examples/blinky_timer_irq.rs

I saw the `blinky_timer_irq.rs` demo that @therealprof wrote in the `stm32f0xx-hal` repo and wanted to poke at it, but I only have a Black Pill (STM32F103) board on hand, so...
I ran this command on the example file:
rustfmt --config imports_layout=HorizontalVertical examples/blinky_timer_irq.rs
and I was almost happy with the results, but not quite.
Obligatory animated GIF, since blinkenleds are so exciting...

examples/blinky_timer_irq.rs: added an '#[interrupt]' blinky demo

---

CHANGELOG.md
src/pwm.rs

Closes https://github.com/stm32-rs/stm32f1xx-hal/issues/165
Also, now we update the `psc` before starting the timers.

Fixes PWM on TIM1

---

examples/spi-dma.rs

`wait` method returns tuple of `(BUFFER, TxDma<PAYLOAD, $CX>)`

spi-dma example: swap buffer and SPI device in return value of a transfer's wait

---

src/lib.rs
src/time.rs

Adds docs for the various time structs. I'm using the nightly doc link syntax as it's easier to throw links to stuff everywhere. Build the docs with `cargo +nightly doc` to see them working. docs.rs already does this so they should render correctly there.
This PR also adds `#![deny(intra_doc_link_resolution_failure)]` for future use. It's a noop in stable but helps with link checking in nightly. Happy to remove if people don't want it in yet.
TODO
Cc #158

Add docs for Hertz structs

---

src/time.rs

From the Rust docs:
> One should always prefer implementing From over Into because
> implementing From automatically provides one with an implementation of
> Into thanks to the blanket implementation in the standard library.

Hertz: Replace Into impls with From impls

---

src/i2c.rs

I added some documentation comments to the I2C module. Most of them are stating the obvious, but hey, better than nothing. Having a little string in the documentation gives me as a reader the feeling, that I'm not completely lost :wink:.
The `pub fn $i2cX` and `pub fn blocking_i2c<I2C, PINS>` functions looked like they are only used internally. So I removed the `pub`, so that they do not appear in the documentation anymore. Compiles and works on my personal project, but maybe this breaks someones code.

Some docstrings for I2C module and non-pub for some apparently internal functions

---

CHANGELOG.md
examples/blinky_timer_irq.rs
examples/usb_serial.rs
examples/usb_serial_interrupt.rs
src/adc.rs
src/gpio.rs
src/lib.rs
src/serial.rs
src/watchdog.rs

Consistently use PAC as `pac`

---

CHANGELOG.md
src/time.rs

This allows the following operations:
- T * u32 (T)
- T *= u32 (T)
- T / u32 (T)
- T /= u32 (T)
- T / T (u32)
It's implemented for the following types:
- Hertz
- KiloHertz
- MegaHertz
- Bps

Impl multiplication and division for frequency wrappers

---

CHANGELOG.md
src/adc.rs

Fixes #201
This was a *fun* bug to track down.
Some decided that it would be a good idea to make one way of starting the ADC conversion to write a `1` to the `adon` bit if the `adon` bit is already one. But that might trigger a read when you want to modify other parts of the register, so this behaviour only happens if no other bits are modified. Thus, `modify` on the `cr2` register will start a conversion unless at least one bit is *actually* modified.
This was accidentally done as the first part of the `convert` function, which started a conversion which would be ready roughly by the time the CPU starts checking for `eoc` bits.
The race condition occurs if the CPU gets to the `EOC` check, before the ADC has time to reset the bit as a result of the `swstart` trigger. This relies on the …

Fix race condition causing ADCs to read stale values

---

src/i2c.rs
src/pwm_input.rs
src/rcc.rs
src/rtc.rs
src/serial.rs
src/spi.rs
src/time.rs
src/timer.rs

Fix clippy lints

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
README.md
src/backup_domain.rs
src/lib.rs
src/pwm.rs
src/pwm_input.rs
src/qei.rs
src/rcc.rs
src/spi.rs
src/timer.rs

This PR adds support for the `stm32f105xx` and `stm32f107xx` devices which are also knows as *connectivity line*.
They have a peripheral configuration similar to the stm32f103 high-density devices but feature USB OTG FS peripheral and the stm32f107xx devices additionally have an ethernet controller.
Both share a common SVD file with the name stm32f107. I introduced the `connectivity` cargo feature to always cover both devices. The `connectivity` feature replaces all previously abandoned `stm32f107` and `stm32f105` features in configuration attributes.
I could blink a LED on a STM32F105 board with a crystal oscillator. No other tests were run on real hardware.
Please have a look and let me know if I missed something and what can be improved.

Support for connectivity line devices (stm32f105 and stm32f107)

---

CHANGELOG.md
examples/crc.rs
src/crc.rs
src/lib.rs
src/prelude.rs

I'm complete newcomer on microcontroller & stm32, so please feel free to comment.
- Tested on `stm32f103c8`
- I'm not sure how it interacts with other peripherals. For example it seems that SPI protocol requires CRC calculation. Does stm32 SPI uses CRC peripherals for CRC calculation of there's another CRC hardware dedicated to SPI CRC?
- I'm not sure if I should use `split` or `constrain`.
- small additional diff on `prelude` caused by `rustfmt`.

initial CRC support

---

src/watchdog.rs

According to RM0008 section 25.4.2 we should support prescaler values up to 256.

Add missing watchdog prescalers.

---

src/i2c.rs
src/serial.rs
src/spi.rs
src/timer.rs

I never liked the RccBus generic stuff, as it made it impossible to tell which register to pass to the constructors of functions, `&mut <USART1 as RccBus>::Bus` isn't very helpful.
This PR goes back to explicit APB1 and APB2 in the constructors, but keeps the generic structs inside functions to still provide most of the benefit while improving doc readbility.
While this is a public API change, I don't believe it is breaking, as it still requires the exact same types to be passed to functions.
cc: @burrbull

Remove generic RCC buses from public API

---

CHANGELOG.md
src/pwm.rs

Fix period retrival for timers

---

CHANGELOG.md
src/afio.rs
src/lib.rs
src/rcc.rs
src/spi.rs

The lack of documentation for how to get a hold of the `Rcc` and `Afio` structs has bothered me for a while. This fixes that, along with adding some top level documentation to the SPI module

Improve SPI, RCC and AFIO documentation

---

.cargo/config
README.md

On Ubuntu from 18.04 it seems that `arm-none-eabi-gdb` is now replaced with `gdb-multiarch` and then `gdb` is used to perform debugging. https://rust-embedded.github.io/book/intro/install/linux.html seems to indicate this might not apply to all distributions though. A `gdb-multiarch` package does exist in the AUR (https://aur.archlinux.org/packages/gdb-multiarch/), and I'm unable to access the fedora website to check.

Change arm-none-eabi-gdb to gdb-multiarch

---

Cargo.toml
examples/blinky_rtcalarm_irq.rs

It is not obvious how to use RTCALARM interrupt. It took me a near an hour to find it in reference manual.

Add blinky_rtcalarm_irq example

---

src/gpio.rs
src/rcc.rs
src/rtc.rs

Like my previous documentation improvement PR, this one adds a few more links where I think that it might be hard to find out where parameters come from, or how to aquire certain structs.
I'll probably do a few more commits as I find them, so don't merge quite yet

More documentation links

---

src/time.rs

Closes #252 
Unfortunately this a breaking change as we now need to take the DCP peripheral when starting the mono timer.
I also added a note from one of the linked issues about `mono_timer` being stopped when hprintln is running.
For reference, here is a code sample that does not work currently, but does with this fix
```rust
#![deny(unsafe_code)]
#![no_main]
#![no_std]
use panic_halt as _;
use cortex_m_semihosting::hprintln;
use cortex_m_rt::entry;
use stm32f1xx_hal::{
pac,
prelude::*,
serial::{Config, Serial},
};
use embedded_hal::digital::v2::OutputPin;
use core::fmt::Write;
#[entry]
fn main() -> ! {
let mut cp = cortex_m::peripheral::Peripherals::take().unwrap();
let p = pac::Peripherals::take().unwrap();
let mut flash = p.FLASH.constrain();
let mut rcc = p.RCC.constrain();
let …
```

Fix mono timer

---

CHANGELOG.md
src/spi.rs

This is an attempt to implement [issue #256](https://github.com/stm32-rs/stm32f1xx-hal/issues/256).
This adds a `PhantomData` tag to the `Spi` objects, allowing them to be typed as `u8` or `u16` to indicate their data frame size. The existing constructor creates a `Spi<..., u8>` object with no change in syntax to not break the existing API. To convert between dataframe modes you must call `frame_size_8bit()` or `frame_size_16bit()` which consumes the old type and hands back the new one.
Example usage:
```
let spi8 = spi::Spi::spi2(dp.SPI2, (sclk, miso, mosi), spi_mode, 100.khz(), clocks, &mut rcc.apb1);
let spi16 = spi.frame_size_16bit();
```
So far there is no way to initialise directly into 16bit data frame mode. I couldn't think of an elegant way without breaking the current API, and …

Spi with 16bit framesize

---

CHANGELOG.md
src/flash.rs

This PR is a followup on #141.

Flash Read/Write Support

---

CHANGELOG.md
src/timer.rs

Implement timer::Cancel trait for CountDownTimer

---

CHANGELOG.md
src/bb.rs
src/lib.rs

Fixes #271 
I also fixed a lint warning that popped up while building on the latest nightly and removed the duplicate categories that are present in CHANGELOG.md
cc: @thalesfragoso

Mark bit banding function unsafe (and some minor fixes)

---

CHANGELOG.md
src/spi.rs

This is necessary in order for SPI3 to function correctly.
Note that this is a breaking change, as it requires access to `MAPR` via
a new argument. This has been added as the third argument to match the
`spi1` constructor.
Tested successfully on an F107.

Add missing SPI3 remap

---

CHANGELOG.md
Cargo.toml
src/adc.rs
src/dma.rs
src/serial.rs
src/spi.rs

Fixes #270 
This PR is pretty much done, but it would be nice to test at least the affected examples on hardware. Unfortunately, I don't have the time to do it right now, I would appreciate some help.
CC @TheZoq2 and @mitchmindtree

Change DMA API to use embedded-dma traits

---

src/lib.rs

Hides `stm32` and `device` from the docs so they don't clutter things too much. Temporary fix for #237 since we still have 75% of users on versions before the deprecation according to crates.io.

Hide PAC aliases to declutter docs

---

CHANGELOG.md
src/spi.rs

Fixes #279
This adds a method to the SPI type which allows configuring which frame format to use for data transfers.

Add SPI frame format config method

---

CHANGELOG.md
src/i2c.rs

Fixes required to work with an AM2320 sensor; This sensor doesn't acknowledge the first i2c message sent to it, but it triggers it to wake up. This caused the i2c state to stay in an error state and the bus not to go idle.  This is fixed in the first two patches
Later on a multi (>2) byte read is necessary  to actually get the data; However the data didn't get properly acknowledged, fixed in the last patch.

various i2c fixes

---

CHANGELOG.md
Cargo.toml
examples/exti.rs
examples/timer-interrupt-rtic.rs
examples/usb_serial_rtic.rs

Following the upstream rename.

Use cortex-m-rtic instead of cortex-m-rtfm

---

CHANGELOG.md
src/spi.rs

This patch allows for OpenDrain configuration on SPI Sck and Mosi pins. This in turn makes it possible to use the SPI interface on 5V bus'es using a simple 5V pull-up (no level shifter).

Added support for SPI Alternate<OpenDrain> configuration on Mosi and Sck pins

---

CHANGELOG.md
Cargo.toml
examples/can-echo.rs
examples/can-loopback.rs
examples/can-rtfm.rs
examples/can-rtic.rs
src/can.rs
src/lib.rs
src/rcc.rs

Replaces #215 
@jonas-schievink refactored the previous PR into a device agnostic driver crate.
Use the new crate to minimize fragmentation between `stm32fxxx-hal` crates.
Draft until I have upstreamed a last missing improvement to masked filters.

Support for CAN peripherals with the `bxcan` crate

---

CHANGELOG.md
src/spi.rs

The remap is available only in connectivity line devices.
Closes #287
https://www.st.com/resource/en/reference_manual/cd00171190-stm32f101xx-stm32f102xx-stm32f103xx-stm32f105xx-and-stm32f107xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf

Fix SPI3 alternate function remapping.

---

CHANGELOG.md
src/rcc.rs

Add DAC, UART4, UART5 clock in RCC for the f103 high density line

---

examples/usb_serial.rs

USB-SERIAL_NOTES: add note to inform user to build in release mode

---

CHANGELOG.md
src/timer.rs

I frequently use timers for precise measurements, and unfortunately, `start_countdown` performs intransparent calculations which can introduce rounding errors.
This PR adds the capability to set and read the raw prescaler and auto-reload values, also we can now read the timer's count; this is useful when ARR is set to `0xFFFF`, i.e. the timer is just "free-running".

Timer additions: raw access to prescaler and auto-reload

---

examples/spi.rs
src/spi.rs

Use only this sequence.
Related to #339.
Need decision. What we need more? Possibility to pass pins in custom sequence or more simple API.
cc @TheZoq2 @therealprof @TeXitoi @adamgreig @thalesfragoso

SCK, MISO, MOSI

---

CHANGELOG.md
src/i2c.rs
src/serial.rs

Fixes #334
I have not tested that code, though, so proceed with caution :)

Do not enable UART DMA flags unconditionally

---

CHANGELOG.md
src/dma.rs
src/prelude.rs
src/spi.rs

Implements #200
SPI is a bit different from most other DMA-supporting peripherals, since SPI in master mode cannot receive without transmitting simultaneously. After some discussion in the #rust-embedded irc channel, we came to the conclusion that `split()`ting the device (like with serial) does not make much sense, because sending and receiving are inherently tied to each other; that made it necessary to finish the implementation of the already-existing (but unused) `RxTxDma` struct from `dma.rs` and add required traits.
This PR does that and adds an RxTxDma implementation to the SPI module.
Because in slave mode, this might(?) be still possible to receive without transmitting, I left the `RxDma` implementations in, but I am yet unsure about this.
Please do tell me if you have any …

Add DMA RX and RX/TX support to SPI

---

Cargo.toml
examples/gpio_input.rs
examples/input_gpio.rs

I not found example about gpio input mode long time, so I written the example to share everyone.

Add example of GPIO input mode

---

CHANGELOG.md
examples/exti.rs
src/gpio.rs

ref: [h7xx](https://github.com/stm32-rs/stm32h7xx-hal/pull/179), [l4xx](https://github.com/stm32-rs/stm32l4xx-hal/pull/187), [f4xx](https://github.com/stm32-rs/stm32f4xx-hal/pull/250), [f7xx](https://github.com/stm32-rs/stm32f7xx-hal/pull/111)

Use CamelCase for gpio::Edge enum variants

---

.cargo/config
examples/i2c-bme280.rs
examples/i2c-bme280/Cargo.toml
examples/i2c-bme280/memory.x
examples/i2c-bme280/src/main.rs

I created this example for my self as a reference for a more complex use of the bme280 sensor. And thought it might be nice to share.
I noted the comments in #24 that it seems like you don't want examples of real hardware, but I don think this is explicitly stated. Would you like a example like this? I might offer it to the bme280 crate but there example is i2c master agnostic, ill just put it on my blog as reference if this is not the place for it, but i think it will be much more easily discoverable here.
You can get bme280 breakout boards for less than £20 in the uk, eg https://thepihut.com/products/adafruit-bme280-i2c-or-spi-temperature-humidity-pressure-sensor so there pretty cheap and cheerful so it seems like a nice thing to use as a example as its cheap and you can see the values …

Example of using i2c with the bme280 air sensor

---

src/adc.rs

add DMA support for ADC3

---

Cargo.toml
examples/serial-interrupt-idle.rs
src/serial.rs

Add serial idle method and example

Add serial is_rxne is_idle is_txe 

---

CHANGELOG.md
src/flash.rs

When erasing a 2kb flash page, flash erase verification wanted all `u16`s with addresses starting from 0 to 2047 to be `0xFFFF`.
This includes the u16 located from 2047 to 2048 (inclusive), which contains the last byte of the to-be-erased page and the first byte of the next page.
Surely, this u16 cannot reasonably be expected to be 0xFFFF after the erase.
Stepping over even addresses only solves this issue.

Fix failing flash verification on erase

---

CHANGELOG.md
src/pwm_input.rs

This fixes #321.
This PR is a subset of #358 and #359.

Allow PullUp and PullDown inputs for timer pwm_input and qei

---

CHANGELOG.md
src/can.rs
src/pwm_input.rs
src/serial.rs
src/spi.rs

This fixes #321, extends on #118, and also fixes this issue for other peripherals that don't mind whether their Inputs have pull-ups or -downs enabled.
This is a superset of #357 and a subset of #358.

Allow all pullup inputs

---

CHANGELOG.md
src/can.rs
src/pwm.rs
src/pwm_input.rs
src/serial.rs
src/spi.rs

This fixes #321, #199 and extends on #118, and also fixes this issue for other peripherals that don't mind which pull-ups are configured for their inputs and whether their outputs are pushpull or open drain.
This is a superset of #357 and #359. Prefer this PR.

Allow pullup inputs and opendrain outputs

---

CHANGELOG.md
src/time.rs

This PR derives `PartialOrd` for types in the `time` module. Which is useful in cases where it is necessary to compare frequencies.
* Derive `PartialOrd` for `Bps`
* Derive `PartialOrd` for `Hertz`
* Derive `PartialOrd` for `KiloHertz`
* Derive `PartialOrd` for `MegaHertz`

Derive PartialOrd for time module types

---

.github/workflows/ci.yml
src/rcc.rs

First goal is to find why #367 
cc @qthree @TheZoq2

pll enable & rcc_config_usb test

---

CHANGELOG.md
src/rcc.rs

dbp can't be written to unless PWRen has been set.

Fix, enable PWR clock before accessing the PWR_CR

---

src/serial.rs

If we use write here one can not use dma with tx and rx at the same time, as the second with_dma() overwrites the register

Use modify instead of write

---

CHANGELOG.md
examples/serial_reconfigure.rs
src/serial.rs

Example use case is to implement a [1-Wire Bus "Master"][1]. In that example, the UART is used instead of bit-banging the 1-Wire protocol. However, not all signals can be generated with a single baud rate. In particular, the 1-wire reset strobe is much longer than the 1-wire data strobes, requiring to use a different, slower baud rate to reset devices.
[1]: https://www.maximintegrated.com/en/design/technical-documents/tutorials/2/214.html

Add support for reconfiguring a Serial port

---

CHANGELOG.md
Cargo.toml
examples/blinky_timer_irq.rs
examples/pwm.rs
examples/pwm_custom.rs
examples/pwm_input.rs
examples/qei.rs
examples/timer-interrupt-rtic.rs
src/timer.rs
src/timer/monotonic.rs

Source:
https://github.com/jhillyerd/hw-cpu/blob/main/firmware/src/mono.rs

timer Instance, rtic monotonic

---

CHANGELOG.md
src/i2c.rs
src/pwm_input.rs
src/rcc.rs
src/serial.rs
src/spi.rs
src/timer.rs

replace GetBusFreq with BusClock

---

src/i2c/blocking.rs

IMO `i2c2` is on PB10 and PB1**1**

Fix a tiny typo in comment

---

CHANGELOG.md
examples/serial_9bits.rs
examples/serial_config.rs
src/serial.rs

~~Depends on #354~~
Instead of #319 
Closes #262 
cc @AndreySmirnov81

Add 9-bits word length mode for serial (new)

---

examples/serial_9bits.rs
examples/serial_config.rs
src/serial.rs

Maybe do the following renaming?
wordlength_8 -> wordlength_8bits
wordlength_9 -> wordlength_9bits
(since there may be not only data bits but also parity)
WordLength::DataBits8 -> WordLength::Bits8
WordLength::DataBits9 -> WordLength::Bits9
And also add 
Config::wordlength(mut self, wordlength: WordLength).

Rename Serial items

---

CHANGELOG.md
Cargo.toml
examples/serial-dma-circ.rs
examples/serial-dma-peek.rs
examples/serial-dma-rx.rs
examples/serial-dma-tx.rs
examples/serial-fmt.rs
examples/serial.rs
examples/serial_9bits.rs
examples/serial_config.rs
examples/serial_reconfigure.rs
src/serial.rs

- Passing the `Clock` parameter to `Serial` by reference.
- `Serial::usart1/2/3` -> `Serial::new`.
- `Serial` implements `Write<WORD>` and `Read<WORD>` for `WORD` simultaneously as u8 and u16.
- Allow access to the `Tx` and `Rx` parts of the `Serial` without the need for splitting.
- Allow `Serial` reconfiguration by references to the `Tx` and `Rx` parts.
- Allow `Serial` release after splitting.
Instead of #414 and #409.

Serial changes v3

---

CHANGELOG.md
src/flash.rs

According to the [errata](https://www.st.com/resource/en/errata_sheet/es096-stm32f101x8b-stm32f102x8b-and-stm32f103x8b-mediumdensity-device-limitations-stmicroelectronics.pdf) for stm32f1, section 2.2.8, reading `BSY` after writing `STRT` needs a 1-cycle delay to be read correctly.
It took a while for us to hit an issue with this (presumably due to eventual optimization by the compiler). Once you hit it, the chip just hangs, as the `while` loop that waits for `BSY` to be cleared immediately completes, which causes the page erase and lock bits are reset while an erase operation is still ongoing, which is probably not good.

Fix flash write error, according to errata

---

CHANGELOG.md
Cargo.toml
examples/can-echo.rs
examples/can-loopback.rs
examples/can-rtic.rs

This pull request bump the version of bxcan from 0.6 to [0.7](https://github.com/stm32-rs/bxcan/releases/tag/v0.7.0), which introduce the second can FIFO. 
All CAN example are updated to use the new version of bxcan.
(I don't know how to add label, but this is a breaking change)

Bump bxcan

---

CHANGELOG.md
src/timer.rs

Adds the `get_interrupt` method to `Timer` (just as it already exists for `FTimer` here: https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/timer.rs#L768)

feat: adds `get_interrupt` to `Timer`

---

CHANGELOG.md
src/timer/pwm.rs

Retrieving timer frequency using PwmHz::get_period() function can cause
division by zero exception for certain types of frequencies which are
configured by having zero in any of the PSC or ARR register - current
implementation uses "clk / (psc * arr)" expression to compute the
frequency.
Implementation of compute_arr_presc() sets PSC and ARR registers
correctly. Performing inverse computation leads to different expression:
"clk / ((psc + 1) * (arr + 1))" which properly computes timer frequency
from PSC and ARR registers. This patch uses new/fixed expression for
computing timer frequency.
Change log was modified.

Fix computation of timer frequency

---

src/rcc.rs

The existence of a crate::rcc::Clocks value is supposed to assert that
the MCU clocks have been configured and that they cannot be changed
anymore. That works by consuming the only instance of CFGR in the
corresponding function and then returning a Clocks value.
However, having crate::rcc::config::Config::get_clocks public implies
that external code can, at any time, generate a Clocks value: by simply
constructing a Config instance (all fields are public) and calling the
function.
```rust
#![no_std]
#![no_main]
use panic_halt as _;
use stm32f1xx_hal as hal;
use cortex_m_rt::entry;
#[entry]
fn main() -> ! {
let clocks: hal::rcc::Clocks = hal::rcc::Config{
hse: Some(8000000),
pllmul: Some(8),
hpre: hal::rcc::HPre::DIV1,
ppre1: hal::rcc::PPre::DIV2,
ppre2: hal::rcc::PPre::DIV1,
adcpre: …
```

Un-publish crate::rcc::Config::get_clocks

---

CHANGELOG.md
src/timer/counter.rs

`CounterHz` and `Counter` do not `wait` properly after the second and subsequent `start`.

Bugfix: `CounterHz` and `Counter` `wait`

---

src/gpio.rs

Allow GPIO splitting without reset and pin output configuration keeping initial state

---

examples/rtc.rs
src/rtc.rs

Hi, I came across a problem when using the Rtc.
The problem is that if the microcontroller is reset, some time will be lost due to the reinitialization of the oscillator.
In order to solve this, I added methods restore_or_new, restore_or_new_lsi, restore_or_new_hse.
These methods check whether the rtc is enabled and the source is correct. If this is the case, the initialization is skipped.
After testing this, (for now, only with lse) it worked as intended, no time was lost anymore and the rtc was still counting.
What do you think about this? Are there any other things needed to be done, or should I change the behavior somehow?

Allow restoring currently running rtc (lost time on initialization)

---

src/gpio.rs

[GPIO doc](https://docs.rs/stm32f1xx-hal/latest/stm32f1xx_hal/gpio/index.html) incorrectly states that in `PullDown` mode the input is connected to **high**.

Fix typos in GPIO docs

---

CHANGELOG.md
src/spi.rs

This removes a compilation error due to the `invalid-reference-casting` check.

Replace UB code by a legitimate pointer access

---

CHANGELOG.md
src/qei.rs

`embedded_hal::Direction` has been removed from recent `embedded_hal` releases. It needs to be reexported from `qei` in order to allow users of `Qei::direction()` to be able to match against the method result if they use a recent `embdded_hal` release.

Reexport Direction from older embedded_hal

---

CHANGELOG.md
src/rcc.rs

Allows to set HSE bypass bit in RCC clock config register to use external clock supplied through OSC_IN pin.
Implementation is adopted from stm32f4xx-hal.
Related to #481

Allow to set HSE bypass bit in clock config

---

CHANGELOG.md
src/rcc.rs

Similar to [this PR in stm32f4xx-hal](https://github.com/stm32-rs/stm32f4xx-hal/pull/231), I am porting a firmware on existing target that was designed to run faster than the official speed. This PR bypass the assert if allow_overclock is set in Config :
```
let clocks = rcc.cfgr.freeze_with_config(Config{
hse: Some(10_000_000),
hse_bypass: true,
pllmul: Some(0b1000),
hpre: HPre::Div1,
ppre1: PPre::Div4,
ppre2: PPre::Div1,
usbpre: UsbPre::Div1,
adcpre: AdcPre::Div8,
allow_overclock: true,
}, &mut flash.acr);
```

Add an option to allow overclocking

---

CHANGELOG.md
src/timer.rs

In practice the only bit we set is CR1.ARPE which enables preloading/buffering of the timer auto reload value. Before this patch we set the bit ([`tim.enable_preload(true)`](https://github.com/stm32-rs/stm32f1xx-hal/blob/21c64d861c29a97753a22afdd06daaea614592c6/src/timer/pwm.rs#L324)) but then immediately unset the bit again when enabling PWM.

Don't overwrite other bits when enabling a PWM timer

---

CHANGELOG.md
README.md

update changelog, add badges

---

CHANGELOG.md
Cargo.toml
examples/adc-dma-circ.rs
examples/adc-dma-rx.rs
examples/adc.rs
examples/adc_temperature.rs
examples/mfrc522.rs
examples/spi-dma.rs
examples/spi-slave.rs
examples/spi.rs
src/adc.rs
src/i2c.rs
src/i2c/blocking.rs
src/rcc/enable.rs
src/spi.rs
src/time.rs

&Clocks instead of Clocks

---

CHANGELOG.md
examples/can-echo.rs
examples/can-loopback.rs
examples/can-rtic.rs
examples/mfrc522.rs
examples/serial-dma-circ.rs
examples/serial-dma-peek.rs
examples/serial-dma-rx.rs
examples/serial-dma-tx.rs
examples/serial-fmt.rs
examples/serial-interrupt-idle.rs
examples/serial.rs
examples/serial_9bits.rs
examples/serial_config.rs
examples/serial_reconfigure.rs
examples/spi-dma.rs
examples/spi-slave.rs
examples/spi.rs
src/can.rs
src/gpio.rs
src/i2c.rs
src/i2c/blocking.rs
src/i2c/hal_02.rs
src/i2c/hal_1.rs
src/prelude.rs
src/serial.rs
src/spi.rs
src/spi/hal_02.rs
src/spi/hal_1.rs
src/timer/pwm.rs

This is breaking change.
It uses similar idea to https://github.com/stm32-rs/stm32f4xx-hal/pull/594 and family, but different.
Istead of `pins: TupleOfPinEnums` peripheral keeps `pins: EnumOfPinTupleCombinations`. It is less beautiful and flexible, but gives workaround for `AFIO` map issues (which is F1 only).
Needs complex testing. cc @all_who_can_test_and_have_ideas :)

remap enums

---

CHANGELOG.md
Cargo.toml
examples/usb_serial.rs
examples/usb_serial_interrupt.rs
examples/usb_serial_rtic.rs
src/lib.rs
tools/check.py

Use the latest version to get implementations of `Read` and `Write` from `embedded-io` for `SerialPort`.

Use latest version of `usb-device` and `usbd-serial`

---

README.md

Fix path for .cargo/config -> .cargo/config.toml in README.md

Fix path for .cargo/config -> .cargo/config.toml

---

CHANGELOG.md
Cargo.toml
src/adc.rs
src/crc.rs
src/dma.rs
src/gpio.rs
src/i2c.rs
src/rcc.rs
src/rtc.rs
src/timer.rs

As per the discussion in #282 
This seems better, but it also leaves the possibility of some flags not being cleared if multiple flags are raised at the same time. Is that something that can even happen, and how should we deal with it then?
CC: @Disasm

Use modify instead of write for clearing sr1

---

CHANGELOG.md
src/adc.rs

This patch allow user enable End of Convert interrupt for ADCs by calling `adc1.enable_eoc_interrupt()`.
Tested on STM32F103CBT6, after enabling the `eocie` register. The interrupt `ADC1_2` is triggered every time ADC convert is finished. This allows more efficient waiting for ADC result.

Add enable/disable EOC interrupt functions for ADCs

---

CHANGELOG.md
examples/usb_serial_rtic.rs

Remove unsafe code from usb_serial_rtic example

---

CHANGELOG.md
src/rtc.rs

So far, `Rtc::select_frequency` did not consider frequencies other than LSE_HERTZ, which was valid only for LSE with 32.768 kHz. For LSI, which has 40 kHz, and HSE, which may have an arbitrary frequency in a given range, the frequency was selected based on the wrong RTC frequency.
This PR aims to fix that. I've also refactored the new methods a bit, using the select_frequency instead of repeating the same code.
I've solved this by adding frequency field to the Rtc, there is no other way I could think of, as HSE frequency may be different depending on the crystal selected for specific application. As far as I understand it, LSE does not necessarily have to be 32.768 kHz, so maybe adding the possibility to change the frequency of LSE could prove useful as well? Adding the frequency field …

Fix RTC selection of frequency for LSI and HSE

---

CHANGELOG.md
src/adc.rs

Previously when an `Adc` is initialized, the temp/vref sensor was disabled. During an ADC read, the sensor has to be turned on and off, which significantly increases the time it takes for a read. Additionally, since there was no way to enable to sensor manually, I don't think it was possible to read VREF in DMA mode.
Now, there are 3 additional functions, `enable_temp_vref`, `disable_temp_vref` and `is_temp_vref_enabled`. These functions are optional, and will speed up reading from the ADC if it is enabled manually. 
The `read_aux` function now also only enables the sensor if the temp or vref channel is being read.
I tested this with an STM32F103 (bluepill)

add temp/vref controls

---

CHANGELOG.md
Cargo.toml
README.md
src/usb.rs

release 0.11
