stm32-rs/stm32f1xx-hal

src/gpio.rs
Allows to set pin to high or low before actual switch to the output mode, eliminating small "low" window in cases where pin should be idle high.
I have tested this with push-pull output. The window is apparent when viewed in a logic analyzer, and this change eliminates it.
Please review thoroughly, as I don't have much expertise in neither Rust nor STM32 :)
=> Add support for setting initial pin state

README.md
=> Add information about device features to readme

CHANGELOG.md, Cargo.toml
=> Added CHANGELOG.md, bumped version and prepare 0.2.0 release

README.md
I think, a link to the docs does not hurt in the readme ;-)
=> Added link to docs.rs to README

src/afio.rs, src/delay.rs, src/dma.rs, src/gpio.rs, src/lib.rs, src/pwm.rs, src/qei.rs, src/rcc.rs, src/serial.rs, src/spi.rs, src/timer.rs
I tried to improve the documentation a bit. (#22)
Please review, as I'm new to this crate and I might have misunderstood things.
The example is adapted from the serial example.
=> Documentation

CHANGELOG.md, src/serial.rs
=> Use correct clock to compute serial baud rate

Cargo.toml, examples/blinky.rs, examples/blinky_rtc.rs, examples/delay.rs, examples/itm.rs, examples/led.rs, examples/mfrc522.rs, examples/nojtag.rs, examples/panics.rs, examples/pwm.rs, examples/qei.rs, examples/rtc.rs, examples/serial.rs, src/afio.rs, src/backup_domain.rs, src/delay.rs, src/dma.rs, src/flash.rs, src/gpio.rs, src/i2c.rs, src/lib.rs, src/prelude.rs, src/pwm.rs, src/qei.rs, src/rcc.rs, src/rtc.rs, src/serial.rs, src/spi.rs, src/time.rs, src/timer.rs
2018 edition path style.
Closes #16 .
=> Edition 2018

src/pwm.rs, src/rcc.rs, src/timer.rs
Thank you @nraynaud for the idea !
=> Implement a way to retrieve timer clocks which is less error prone

CHANGELOG.md, src/serial.rs
Closes #18, all credit to @therealprof.
=> feat: fmt::Write for serial Tx

src/pwm.rs
Another doc improvement, this time for the pwm module. It would be nice if someone could read through it to make sure I didn't mess anything up :)
=> Add pwm usage instructions

CHANGELOG.md, src/lib.rs, src/time.rs, src/watchdog.rs
This is pretty much the same as https://github.com/stm32-rs/stm32f4xx-hal/pull/83
=> Add IWDG Watchdog implementation

CHANGELOG.md, Cargo.toml, src/lib.rs
=> Added device-selected meta feature flag

README.md
=> Update the cargo version in the README.md

CHANGELOG.md, src/gpio.rs
=> Remove OutputPin impl for Alternate mode pins

src/usb.rs
@Disasm Since you wrote the module, could you make sure I didn't make any obvious misstakes here?
=> Add rudimentary docs for the usb module

Cargo.toml
=> Unbump as_slice

src/timer.rs
- fix typo in TIM2 pin description
- add Tim1FullRemap pins selection
=> Updates for timer doc sections

CHANGELOG.md, src/gpio.rs
=> Add InputPin impl for generic open drain outputs

CHANGELOG.md
=> Add QEI changelog entry

.github/workflows/ci.yml, Cargo.toml, examples/delay.rs, examples/led.rs
This also improves the required-features selection for the examples.
=> Rework examples to apply to more targets and test in CI

examples/blinky_timer_irq.rs
=> Cleanup blinky_timer_irq example.

src/rtc.rs
Addresses some issues I found while trying to use the RTC. Most importantly, that the RTCALARM interrupt is not what it sounds like.
I also moved the module level docs to the RTC struct itself since that's where I find it most natural to look.
Finally, I removed the section on it requiring the backup domain to be initialised correctly as that is guaranteed by the type system and felt confusing to me
=> improve RTC documentation

src/time.rs
Fix error in description of Megahertz
=> Fix small mistake in time.rs: kilohertz should be megahertz

CHANGELOG.md, src/adc.rs
Adds support for continuous scan mode (solves issue #212).
Also adds support for discontinuous conversion.
Different approach than #214. This PR does not break existing API.
=> Added support for continuous and discontinuous scan mode

src/rcc.rs
=> Add ADC2 clock in RCC for the connectivity line

examples/pwm.rs
...as its missing the call to enable the PWM output on a channel
=> Fix PWM example 

src/serial.rs
Add serial port Idle interrupt.
=> Add serial port Idle interrupt

CHANGELOG.md, Cargo.toml
=> bxcan update

CHANGELOG.md, examples/blinky_rtc.rs, examples/blinky_rtcalarm_irq.rs, examples/rtc.rs, src/rtc.rs
It has been verified that all three RTC clock sources can work.
=> RTC clock source can be selected

.gitattributes, Cargo.toml, examples/can-echo.rs, examples/can-loopback.rs, examples/can-rtic.rs
~~Temporary disables `can-echo` & `can-rtic`~~
Fixes #378
=> update & clean deps

src/serial.rs
=> Make serial reconfigure infallible

src/gpio.rs
Simple change - allows using interrupts with Dynamic pins.
=> Add Interruptable for Dynamic

CHANGELOG.md, examples/adc.rs, src/adc.rs
=> Connectivity line devices config supports ADC2

examples/serial-interrupt-idle.rs
=> Fix a spell mistake

src/gpio/erased.rs
=> revert erased macro

src/gpio.rs, src/gpio/erased.rs, src/gpio/partially_erased.rs
Please merge if you agree with the changes.
=> Small `gpio` changes

CHANGELOG.md, README.md
On Windows add the .gitinit may not be enough.
On my case i have lost at least a few hours before i give up, for the next day i discovery that just because a restart my computer fixed all.
=> Clarify README for windows users

CHANGELOG.md, src/dma.rs, src/serial.rs, src/spi.rs
TODO: investigate how to unmacro Serial::DMA, Spi::DMA
=> unmacro DMA

src/pacext/uart.rs
=> Fix mismatched fn name
